-- Cuales son las canciones mas escuchas en enero de 2022
SELECT *
FROM (
  SELECT COUNT(*) AS SUMA, E.ID_CAN
  FROM ESCUCHA E
  INNER JOIN CANCION C ON E.ID_CAN = C.ID_CAN
  WHERE EXTRACT(YEAR FROM E.FECHA_HORA) = 2022 AND EXTRACT(MONTH FROM E.FECHA_HORA) = 1
  GROUP BY E.ID_CAN
  ORDER BY SUMA DESC
) 
FETCH FIRST 5 ROWS ONLY;

-- Cual es el genero con mas me gusta
SELECT MAX(SUB.CANTIDAD), SUB.NOMBRE
FROM (
  SELECT COUNT(*) AS CANTIDAD, T.NOMBRE
  FROM USUARIO U
  INNER JOIN GUSTA G ON U.ID_US = G.ID_US
  INNER JOIN CANCION C ON G.ID_CAN = C.ID_CAN
  INNER JOIN ALBUM A ON C.ID_ALB = A.ID_ALB
  INNER JOIN TIPO T ON T.ID_ALB = A.ID_ALB
  GROUP BY T.NOMBRE
) AS SUB
GROUP BY SUB.NOMBRE
HAVING MAX(SUB.CANTIDAD) = (
  SELECT MAX(SUBB.CANTIDAD)
  FROM (
    SELECT COUNT(*) AS CANTIDAD
    FROM USUARIO U
    INNER JOIN GUSTA G ON U.ID_US = G.ID_US
    INNER JOIN CANCION C ON G.ID_CAN = C.ID_CAN
    INNER JOIN ALBUM A ON C.ID_ALB = A.ID_ALB
    INNER JOIN TIPO T ON T.ID_ALB = A.ID_ALB
    GROUP BY T.NOMBRE
  ) AS SUBB
)

-- Usuarios que tienen una cancion de Adele en al menos una de sus playlists
SELECT U.*
FROM ARTISTA A
INNER JOIN ALBUM AL ON AL.ID_ART = A.ID_ART
INNER JOIN CANCION C ON C.ID_ALB = AL.ID_ALB
INNER JOIN CONTIENE CO ON C.ID_CAN = CO.ID_CAN
INNER JOIN PLAYLIST P ON P.ID_US = CO.ID_US
INNER JOIN USUARIO U ON U.ID_US = P.ID_US
WHERE A.NOMBRE = 'Adele'

-- Que canciones escucho el 1 de enero de 2022 el usuario de id 5
SELECT C.*
FROM USUARIO U
INNER JOIN ESCUCHA E ON E.ID_US = U.ID_US
INNER JOIN CANCION C ON C.ID_CAN = E.ID_CAN
WHERE 
U.ID_US = 5 AND
EXTRACT(YEAR FROM E.FECHA_HORA) = 2022 AND 
EXTRACT(MONTH FROM E.FECHA_HORA) = 1 AND 
EXTRACT(DAY FROM E.FECHA_HORA) = 16

-- Integrantes de queen y los instrumentos que toca
SELECT M.NOMBRE AS MUSICO, Q.NOMBRE AS INSTRUMENTO
FROM ARTISTA A
INNER JOIN INTEGRANTE I ON I.PROYECTO = A.ID_ART
INNER JOIN ARTISTA M ON M.ID_ART = I.MUSICO
INNER JOIN QUETOCA Q ON M.ID_ART = Q.MUSICO AND Q.FECHA_INICIO = I.FECHA_INICIO AND Q.PROYECTO = I.PROYECTO
WHERE A.NOMBRE = 'Queen'

-- Album mas largo
SELECT MAX(A.DURACION), A.ID_ALB
FROM ALBUM A
GROUP BY A.ID_ALB
HAVING MAX(A.DURACION) = (
  SELECT MAX(AL.DURACION)
  FROM ALBUM AL
)

-- Musicos que no cantan
SELECT *
FROM ARTISTA A
WHERE A.ID_ART NOT IN (
  SELECT AR.ID_ART
  FROM ARTISTA AR
  INNER JOIN INTEGRANTE I ON I.MUSICO = AR.ID_ART AND AR.TIPO = 's'
  INNER JOIN QUETOCA Q ON I.PROYECTO = Q.PROYECTO AND I.MUSICO = Q.MUSICO AND Q.FECHA_INICIO = I.FECHA_INICIO
  WHERE Q.NOMBRE = 'Voz'
)
AND 
A.TIPO = 's'